### ISSUE TITLE
Встречи без презентаций

### ISSUE THREAD

**Issue by inca** [kurskmeetup/meetups#20]
Здрасьте, дорогие друзья,

Предлагаю Вашему вниманию пьесу из трех частей.
## Часть 1: The Excuse

Для начала двухминутный уход от темы: в последнее время я не могу посещать наши прекрасные эвенты по личным/семейным обстоятельствам. Уверяю вас, это никак не связано с отсутствием личного интереса, неуважением к докладчикам или пренебрежением к поднимаемым вами вопросам. Я с большим удовольствием просматриваю ваши презентации и даже швыряю ссылки некоторым знакомым. Верьте: ваши труды не напрасны!
## Часть 2: The Rationale

Теперь, если позволите, преамбула к предложению. [Михон](https://github.com/diversiya) собрал нас всех, затем друзья привели друзей, наше сообщество заметно выросло в очень короткие сроки, и нам всем очень приятно регулярно встречать большое количество знакомых умных людей. Есть, однако, видение некоторой сложности: все мы разные. Подозреваю, строгим адептам C# и программирования окон под Windows немного скучновато слушать про переизобретенный односторонний поток данных при программировании мобильных приложений под Android. Есть среди нас люди, которые интересуются программированием контроллеров под CLion, им не всегда интересно слушать про перспективы ES6 и прочие новомодные аспекты веб-программизма. Обратное также справедливо.
## Часть 3: The Offer

Как насчет чередования событий? Пусть одно из двух будет происходить в существующем формате (презентации, затем разговоры), а второе из двух будет представлять собой "кружки по интересам": объявляем несколько тем бесед (например, «1: Архитектурные подходы в React.js», «2: Самая чистая функция», «3: Как правильно переносить фигурные скобки»); каждый чувак, который решается прийти, готовится как минимум по одной теме (можно две, три или все десять) и приходит. На месте же организуем несколько столиков, куда и будем рассаживать всех желающих подискутировать.

Подготовить можно все, что угодно: кто-то может показать свой проект; кто-то может просто прочитать все, что может найти по этой теме; кто-то может сделать туториал — à vous à décider.

Желательно, чтобы каждый согласившийся также отметился, что придет (r.s.v.p).

Тем самым мы выигрываем сразу в нескольких аспектах:
- никого не обижаем своим отсутствием (да, я все еще чувствую себя неловко);
- способствуем формированию групп по интересам;
- снижаем формальность обстановки, создавая комфортную атмосферу для интровертов (коих большинство);
- не поощряем гордыню, которой итак в нас предостаточно.

Дополнительно можно установить регламент встреч, чтобы исключить холивары и производные.

/cc @vast @diversiya @daynin @pakon @cleverfox @abtv @eluck Будет здорово услышать ваше мнение.

**Comment by mihonninja** [comment]
Я думаю, что идея имеет право на жизнь.
Нужно попробовать собрать пару-тройку раз предложенный тобой формат, чтобы понять плюсы и минусы. 
Хотя, на мой взгляд, очевидна ситуация при которой будет два стола с кучей народа и пять-шесть с одним человеком. Да и подготовка доклада, как видно из имеющейся стати не покрывает пока и половины наших участников. Посмотрим, что думают остальные.

**Comment by pakon** [comment]
Я думаю, что нет большого смысла добавлять кружки по интересам. А вот немного изменить регламент смысл есть, многочасовые презентации действительно немного утомительны, а вот более короткие, посвященные более узкому вопросу - это имхо правильный путь. Большие темы можно разбивать на серии.

Основой является общение, пусть и людей из разных областей. Мне например было бы интересно послушать доклад из области 1С, например :) Делиться по интересам по моему мнению неправильный путь.

**Comment by abtv** [comment]
Я думаю, что любой доклад из совершенно незнакомой области для большинства - типа 1с или микроконтроллеров - не уложится в рамки обычного доклада на 5-10 минут. Возможно, для таких случаев можно расширять временные рамки. А для обычного доклада 10 минут и кучи ссылочек на почитать и посмотреть в конце доклада будет достаточно. Насчет кружков - возможно веб/js съест всех, но нужно пробовать, главное, чтобы докладчик не был один за пустым столом, можно голосовать за тему.

**Comment by inca** [comment]
> на мой взгляд, очевидна ситуация при которой будет два стола с кучей народа и пять-шесть с одним человеком
> 
> главное, чтобы докладчик не был один за пустым столом

Поэтому я и предложил модель RSVP, когда участники за 3-4 дня отписываются, подтверждая свое намерение прийти.

**Comment by daynin** [comment]
На мой взгляд, стоит как минимум пару раз попробовать, чтобы понять будет ли такой формат работать. Формат довольно интересный. Позволит всем, кто хочет высказаться, - высказаться, а кто не хочет - посидеть и послушать. Может просто сложиться ситуация, когда за столом будет сидеть 4 человека, но только один из них будет что-то говорить.

Так или иначе нам стоит пробовать новые форматы, чтобы разнообразить встречи. Тем более к этому формату встреч проще подготовиться, а значит у активных докладчиков будет больше времени, чтобы подготовить "обычный" доклад более качественно.

> Насчет кружков - возможно веб/js съест всех

@abtv я так не думаю. Мне, например, было бы интересно поговорить не о вебе/js. Просто в последнее время так получается, что все доклады о вебе. Хотя на крайней встрече мы классно поговорили о docker'e в частности и вообще о devops. 

Был бы инициатор, а поговорить мы всегда рады :smile:

**Comment by cleverfox** [comment]
На митапах в текущей конфигурации хорошо то, что можно узнать что-то новое, в том числе, из мало интересных областей, что определённо расширяет кругозор. 
И этим они ценны. А в случае, если реализовать вариант Бориса, многие интересные вещи могут пройти мимо. 
К сожалению у меня тоже сейчас большой напряг со временем :(

**Comment by vast** [comment]
Самый верный способ узнать, сработает это или нет, — попробовать. @inca, возьмешься составить список "интересов" для первой такой встречи?
