### ISSUE TITLE
RSVP на 08.08.2015

### ISSUE THREAD

**Issue by inca** [kurskmeetup/meetups#21]
В продолжение #20 приглашаю к обсуждению на следующие темы:
1. React
   - подходы к построению приложений (чем плох Flux и что использовать вместо)
   - хорошие и плохие практики
   - гайдлайны по написанию компонентов
2. ES6/: различные способы flow control, генераторы, async/await и все остальное, что грядет

Также интересно послушать про devops, но предложить темы бесед не готов.

**Comment by inca** [comment]
Пожалуйста, не стесняйтесь предлагать свои темы. Спасибо!

**Comment by daynin** [comment]
@inca , а что делать, если обе темы классные и хочется и туда и туда? :smile:

**Comment by inca** [comment]
@daynin обсуждаем два варианта:
1. голосуем и выбираем одну из них (в течение этой недели), другую откладываем на следующую встречу;
2. принимаем обе и выделяем на каждую, скажем, по часу (это хорошо в том случае, если состав участников примерно одинаковый)

**Comment by inca** [comment]
Кстати, план обсуждения, как видите, весьма примерный. Это нужно просто для того, чтобы можно было начать. А дальше пусть беседа сама идет в ту или иную сторону.

**Comment by daynin** [comment]
Может еще рассмотреть третий вариант: выбираем обе, и они идут параллельно? Каждый участник может проголосовать за ту тему, в обсуждении которой будет участвовать.

**Comment by inca** [comment]
@daynin Ты имеешь в виду, соединить их? Потому что мне тоже интересны обе темы :smile:

**Comment by daynin** [comment]
@inca , нет, именно не соединить, а разбить участников на две независимые группы. Может же оказаться, что не всем интересно обсуждать React. Тут разница в том, что, если мы "объединямем" всех людей для обсуждения всех тем, то незаинтересованному человеку придется слушать неинтересную для него тему. С другой стороны, если распределить темы по группам и разрешить человеку участвовать только в обсуждении одной темы, то он может пропустить что-то интересное из другой темы. В обоих случаях есть плюсы и минусы. Надеюсь, что не запутал окончательно :smile:

**Comment by inca** [comment]
@daynin я вижу, что проблему не распутать без какого-то компромисса: в первом случае ты можешь пропустить что-то интересное, во втором случае ты имеешь вероятность присутствовать на неинтересной теме.

Для этого мы и собираем подтверждения: если на обе темы подписались одни и те же люди, то распараллелить их не получится: нужно либо пускать их последовательно, либо откладывать одну из них, либо соединять в одну (если они родственные).

Пикантнее ситуация, когда тебе вдруг стало интереснее, о чем говорят за соседним столом :smile:

**Comment by daynin** [comment]
@inca , да и вероятность такой ситуации велика. Чтобы не переливать сейчас воду из пустого в порожнее, я проголосую за обе темы (за последовательное их обсуждение: по часу на каждую или с переносом на следующую встречу - не так важно):

**React**
**ES6**

Посмотрим, что скажут другие и примем решение.

**Comment by vast** [comment]
+1 к Реакту

**Comment by abtv** [comment]
React

**Comment by mihonninja** [comment]
React

**Comment by eluck** [comment]
+1 за meetup. Я собираюсь прийти, независимо от формы проведения (к обсуждению посещаемости августовских митапов). Ещё темы будут, или на одной остановимся?

**Comment by eluck** [comment]
У меня, допустим, есть следующий животрепещущий вопрос - что полезного послушать. От смотрения в экран глаза периодически вываливаются, поэтому иногда хочется расслабиться, налить джина с тоником и послушать какой-нибудь технический подкаст. В моём случае это - Радио-Т. А в вашем? Обсудим?

**Comment by daynin** [comment]
@eluck , я, в принципе, очень даже за то, чтобы обсудить подкасты после реакта! (Оставлю это до субботы, но для затравки скажу, что Радио-Т - , как по мне, не очень хороший подкаст **для программиста** :smile:  )

**Comment by eluck** [comment]
ХЗ, может быть, я бы до сих пор админил, если бы не слушал их. Так что он скорее вреден для популяции админов :)

**Comment by pakon** [comment]
Radio-T, CTOcast, Developer Tea, Umputun, budam, Ruby NoName podcast, Разбор полетов, Apptractor, Янки после пьянки (теперь это Подкаст на трезвую голову) - моя подборка подкастов на околотехническую тему.

**Comment by inca** [comment]
Если не будет еще тем, то просто собьемся все в одну кучу и будем обсуждать React, даже если кто-то не хочет :smile:
