### ISSUE TITLE
Нет единого источника информации

### ISSUE THREAD

**Issue by daynin** [kurskmeetup/meetups#22]
Как мне кажется, сейчас существует следующая проблема: у нас нет единого места общения. Люди, сидящие в ВК, не заходят на github, а люди, которые активно что-то обсуждают в github'e, не заходят в ВК. Есть еще люди, которые в основном пользуются twiiter'ом (правда они и на github заходят). При этом всем информация, которая появляется в ВК, отсутствует на github и наоборот.

Предлагаю сделать следующее:
- выбрать ответственного человека (людей) за дублирование информации во всех источниках;
- создать twitter-аккаунт, куда автоматически постить посты из ВК. Либо же опять же просто дублировать наиболее важные посты туда, плюс разбавлять полезными репостами/материалами;

Может быть вы предложите что-то еще.

/cc @inca @vast @diversiya @pakon @cleverfox @abtv @eluck . Что скажете?

**Comment by inca** [comment]
Я за единый источник информации — здесь. И голосую за удаление группы из ВК :imp:

**Comment by daynin** [comment]
@inca , так, наверно, не получится сделать. Там все же 57 человек в группе :). Большая часть людей именно оттуда что-то узнает. Мне кажется, что есть смысл по максимуму дублировать информацию во всех источниках. github + vk + twitter покроют, наверно, 99% потенциальной аудитории

**Comment by onthefly** [comment]
Напишите бот, который отсюда будет постить в твитер и вк, делов-то

**Comment by daynin** [comment]
Отсюда постить что? Issues?

**Comment by daynin** [comment]
@onthefly концепция issues, на мой взгляд, не очень ложится для публикации новостей, вопросов и просто каких-либо постов

**Comment by onthefly** [comment]
@daynin коммиты с темами прежде всего. Первый комментарий в этом issue вполне мог бы послужить отправной точкой для обсуждения где угодно

**Comment by daynin** [comment]
@onthefly , дело в том, что не каждый issue может являться темой, и не каждый commit может нести полезную информационную нагрузку. Так что просто ретранслировать каждый issue и commit не получится :disappointed: 

Конечно, можно ввести специальные маркеры для issue и коммитов, которые стоит публиковать в ВК - #vk или что-то типо того.

У кого какие еще мысли есть по этому поводу?

**Comment by abtv** [comment]
Может, воспользоваться slack'ом?

**Comment by daynin** [comment]
@abtv , а разве у слака есть интеграция с ВК и твиттером?

**Comment by abtv** [comment]
Там есть очень много видов интеграции, но контакта , само собой, нет. Но есть интеграция с твиттером, гитхабом, дропбоксом, хэнгаутом.

**Comment by abtv** [comment]
Хотя нет, Slack интегрирует Твиттер и гитхаб, но создаст еще один источник :) так что это тоже половинчатое решение.

**Comment by daynin** [comment]
В таком случае, действительно, самое верное решение - это бот. Только вот остается вопрос - постить все или только помеченное каким-нибудь тэгом?

**Comment by mihonninja** [comment]
Однозначно не всё подряд. Смысл в том, что нужны только заголовки важных событий.
- расписание
- новые обсуждения (не все посты в топике, а только первый)

Я бы предложил не копировать информацию, а сделать простую почтовую рассылку. Почтой пользуются все. Вообще все, если они хоть как-то связаны с IT.

**Comment by daynin** [comment]
Как синхронизировать расписание при помощи бота еще нужно подумать. А вот простой репост новых Issues и Pull Requests - это довольно просто сделать. В принципе, я могу в свободное время накидать небольшого ботика, который бы хостился на Heroku + Mongolab и делал репосты в ВК. Только мне, скорее всего, понадобится доступ к группе в ВК

@diversiya , можно решить как-нибудь вопрос с группой в ВК?

**Comment by onthefly** [comment]
@diversiya гитхаб и так шлёт всё почтой, вряд ли стоит дублировать это дополнительной рассылкой

**Comment by daynin** [comment]
Изучил вопрос с API VK. Он не позволяет написать server side app, который мог бы постить на стену. Единственный вариант - использовать phantom.js для эмуляции client side app, который бы авторизовался под каким-то пользователем и отправлял бы посты на стену. Прямо грусть-тоска с этим ВК :disappointed:

**Comment by cleverfox** [comment]
Забить на этот ВК. У нас, в конце концов, туса программистов. А уж программист, я думаю, в состоянии зарегаиься на гитхабе.
