### ISSUE TITLE
Выездная встреча на природе

### ISSUE THREAD

**Issue by lyk0rian** [kurskmeetup/meetups#23]
Предлагаю одну из ближайших встречь провести в виде выездного алкогольного мероприятия на природе (пока еще лето не кончилось). Что скажете?

**Comment by daynin** [comment]
@lyk0rian , мне кажется, что это довольно сложно в плане организации. Да и одно дело собраться в центре города, куда каждый может заскочить на час-два, а другое - выехать на природу на значительно большее время.

Возможно я не прав, но я думаю, что пока достаточно митапов в Лекториуме. Поправьте меня, если я не прав

**Comment by onthefly** [comment]
22 августа будет очередной музыкальный пикник на Сейме, можно присоединиться

**Comment by inca** [comment]
Я пока солидарен с @daynin, попросту не могу выкроить время :(

**Comment by mihonninja** [comment]
Я не горю желанием, честно сказать. Масса проблем с организацией, да и это не особенно вяжется с нашей общей идеей "становится лучше".

**Comment by lyk0rian** [comment]
ок. нет, так нет.

btw, последняя встреча по формату мне напомнила такое мероприятие как "сисопка". По этому и спросил мнение народа.
