### ISSUE TITLE
Голосуем за темы для очередного "Круглого стола"

### ISSUE THREAD

**Issue by daynin** [kurskmeetup/meetups#24]
1. Тестирование (юнит, функциональное, интеграционное, нагрузочное). В каких пропорциях какие тесты пишите. Как тестируете фронт? Сontinuous integration или даже continuous delivery?
2. Ваш workflow. IDE vs Vim/Emacs/Sublime etc. Почему выбрали X, а не Y. Плюсы и минусы использования IDE или редакторов.
3. Есть ли жизнь во фронте без JS? Давайте обсудим адекватные замены JS: coffee, TS. А что скажете о разных диковинках типа PureScript, Elm?
4. Базы данных. Что предпочитаете использовать вообще? А что предпочитаете, когда нужен NoSQL/KV. Какую базу выбрать для быстрого прототипирования/стартапа? Mongodb, RethinkDB, CouchDB. Что используете (и используете ли вообще) для клиентского хранения данных? PouchDB?

P.S.

Предлагайте свои темы тоже!

**Comment by abtv** [comment]
Голосую за тестирование и базы данных

**Comment by mihonninja** [comment]
Я за тестирование.

**Comment by vast** [comment]
+1 к тестированию

**Comment by inca** [comment]
Это завтра, так? Я не приду, так что оставляю голос за базы данных (предлагаю эту тему отложить до следующего раза, т.к. с тестами вы вряд ли уложитесь в одну встречу).
