### ISSUE TITLE
Темы для круглого стола на 05.09.2015

### ISSUE THREAD

**Issue by daynin** [kurskmeetup/meetups#25]
1. Ваш workflow. IDE vs Vim/Emacs/Sublime etc. Почему выбрали X, а не Y. Плюсы и минусы использования IDE или редакторов.
2. Есть ли жизнь во фронте без JS? Давайте обсудим адекватные замены JS: coffee, TS. А что скажете о разных диковинках типа PureScript, Elm?
3. Базы данных. Что предпочитаете использовать вообще? А что предпочитаете, когда нужен NoSQL/KV. Какую базу выбрать для быстрого прототипирования/стартапа? Mongodb, RethinkDB, CouchDB. Что используете (и используете ли вообще) для клиентского хранения данных? PouchDB?

P.S.

Предлагайте свои темы тоже!

**Comment by daynin** [comment]
Я за БД

**Comment by mihonninja** [comment]
IDE не очень обширная тема.
Я за БД.

**Comment by daynin** [comment]
@diversiya , ну это как посмотреть :) Если только поставить вопрос Vim vs WebStorm, то уже можно на пару часов холивар затеять :)

**Comment by mihonninja** [comment]
@daynin, так-то да, но помимо холиваров хочется немного конструктива :)

**Comment by daynin** [comment]
@diversiya , согласен. Поэтому я тоже выбрал DB

**Comment by abtv** [comment]
- БД
