### ISSUE TITLE
Темы очередного круглого стола ( 19.09.2015 )

### ISSUE THREAD

**Issue by daynin** [kurskmeetup/meetups#28]
1. Ваш workflow. IDE vs Vim/Emacs/Sublime etc. Почему выбрали X, а не Y. Плюсы и минусы использования IDE или редакторов.
2. Есть ли жизнь во фронте без JS? Давайте обсудим адекватные замены JS: coffee, TS. А что скажете о разных диковинках типа PureScript, Elm, ClojureScript?
3. Open Source деятельность. Как найти время? Как начать свой проект? Как влиться в чужой проект?
4. DevOps: жизни на грани системного админтсва! Как сделать так, чтобы тесты запускались за тебя? Как сделать так, чтобы деплой не был головной болью?
5. Продуктивность во все поля. Как ее повысить? Лайфхаки и прочее для повышения личной и профессиональной продуктивности.

**Comment by abtv** [comment]
DevOps и/или продуктивность

**Comment by daynin** [comment]
:+1:  за DevOps

**Comment by mihonninja** [comment]
DevOps или JS

**Comment by lyk0rian** [comment]
devops.

Кстати, сделайте отдельное объявление на счет места проведения. А то в readme до сих пор про четырехэтажное здание с лабораториумом написано.

**Comment by sineveel** [comment]
JS

**Comment by vast** [comment]
JS. Был бы рад поучиться у крутых ребят собирать фронтенд на ноде.

**Comment by aiserg** [comment]
JS
