### ISSUE TITLE
Слак

### ISSUE THREAD

**Issue by vast** [kurskmeetup/meetups#29]
Ребята!

Чтобы обсуждать предстоящие и прошедшие митапы, делиться интересными ссылками и фотографиями, консультироваться с коллегами и трепаться "за жизнь", я завел ~~публичный канал в Телеграме~~ комьюнити в Слаке: https://kurskmeetup-slackin.herokuapp.com/

Присоединяйтесь, скучно не будет.

**Comment by onthefly** [comment]
![2015-09-23 13 43 38](https://cloud.githubusercontent.com/assets/969593/10043126/24dcfd96-61f9-11e5-86fd-5b9ec366874b.png)
![2015-09-23 13 43 13](https://cloud.githubusercontent.com/assets/969593/10043127/250b6244-61f9-11e5-97a1-fb4eee95f5c3.png)

**Comment by vast** [comment]
@onthefly, прости, Телеграм совсем не подходит для этой задачи. Мы переехали в Слак: https://kurskmeetup-slackin.herokuapp.com/
